### ISSUE TITLE
Null Pointer in SingleTapConfirmedGestureRecognizer.kt:135

### ISSUE THREAD

**Issue by eugene-rsi-europe** [Esri/arcgis-maps-sdk-kotlin-samples#203]
# Null Pointer in SingleTapConfirmedGestureRecognizer.kt:135

## Feature or Bug?
Bug in [ComposeMapView](https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/blob/6008ed17ec1e357fbc6f80b80b46452afd401163/show-callout/src/main/java/com/esri/arcgismaps/sample/showcallout/components/ComposeMapView.kt)

```
arcgis-maps-kotlin = { group = "com.esri", name = "arcgis-maps-kotlin", version = "200.3.0" }
```

##  Behavior

Open/close map very fast. 
For that you should have Box with map, 
and any other composable with button to open map.
Map should have button to close itself.

## Log

```
FATAL EXCEPTION: main (Ask Gemini)
Process: com.rsieurope.app, PID: 25888
java.lang.NullPointerException: A null pointer.
	at com.arcgismaps.internal.ErrorFactoryKt.toPlatformExceptionOrNull(ErrorFactory.kt:200)
	at com.arcgismaps.internal.ErrorFactoryKt.convertToPublic(ErrorFactory.kt:110)
	at com.arcgismaps.internal.ErrorFactory.createThrowableFromCoreError(ErrorFactory.kt:58)
	at com.arcgismaps.internal.jni.CoreGeoView.nativeGeometryEditorInteractionTap(Native Method)
	at com.arcgismaps.internal.jni.CoreGeoView.geometryEditorInteractionTap(CoreGeoView.java:399)
	at com.arcgismaps.mapping.view.GeoView.geometryEditorTap$arcgis_maps_kotlin_release(GeoView.kt:1242)
	at com.arcgismaps.mapping.view.internal.DefaultMapViewOnTouchListener.onRecognizerSingleTapConfirmed(DefaultMapViewOnTouchListener.kt:291)
	at com.arcgismaps.mapping.view.internal.DefaultMapViewOnTouchListener.access$onRecognizerSingleTapConfirmed(DefaultMapViewOnTouchListener.kt:79)
	at com.arcgismaps.mapping.view.internal.DefaultMapViewOnTouchListener$onLifecycleReady$$inlined$launchAndCollectInMapViewResumed$2$1$1.emit(FlowExtensions.kt:5
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:231)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:187)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:159)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:504)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:493)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
	at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:409)
	at com.arcgismaps.mapping.view.internal.SingleTapConfirmedGestureRecognizer.emitSingleTapConfirmed(SingleTapConfirmedGestureRecognizer.kt:163)
	at com.arcgismaps.mapping.view.internal.SingleTapConfirmedGestureRecognizer.access$emitSingleTapConfirmed(SingleTapConfirmedGestureRecognizer.kt:47)
	at com.arcgismaps.mapping.view.internal.SingleTapConfirmedGestureRecognizer$onTouch$2.invokeSuspend(SingleTapConfirmedGestureRecognizer.kt:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:231)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:164)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:504)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:493)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:591)
	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:15)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)

                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@86b9917, Dispatchers.Main.immediate]
Caused by: com.arcgismaps.exceptions.ArcGISExceptionImpl: message=A null pointer., additionalMessage=object cannot be null., errorCode=1
	at com.arcgismaps.exceptions.ArcGISException$Companion.create$arcgis_maps_kotlin_release(ArcGISException.kt:86) (Ask Gemini)
	at com.arcgismaps.internal.ErrorFactoryKt.convertToPublic(ErrorFactory.kt:126)
	... 37 more
[Application Error: com.rsieurope.app#0](this:0xb400007c93f5c898,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Application Error: com.rsieurope.app#0'




```

**Comment by gunt0001** [comment]
Thanks for reporting this @eugene-rsi-europe . We are aware of this issue, which has also been reported on [GeoNet](https://community.esri.com/t5/kotlin-maps-sdk-questions/app-crash-when-user-tapped-on-compose-mapview/m-p/1552200#M511). We are currently trying to come up with a reproducer. To clarify your repro steps:

> Map should have button to close itself.

Do you mean there should be a button that toggles a boolean, if `true`, the MapView is added to the composition and if `false`, the MapView is removed from the composition? Then toggle this button fast?

If you could share a code snippet of your reproducer that woul be helpful.

Also note that your link to the sample points to an older version (200.3.0). As of 200.4.0, there is a composable MapView available in the [Kotlin toolkit](https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/tree/main/toolkit/geoview-compose), which is also used by the [most recent version](https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/blob/main/show-callout/src/main/java/com/esri/arcgismaps/sample/showcallout/screens/MainScreen.kt#L52) of that sample.

**Comment by eugene-rsi-europe** [comment]
@gunt0001 this can be closed since I did not notice this crash for a long time.
